// <auto-generated />
using System;
using Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Ispu.Gis.EnergyBalances.Infrastructure.Migrations
{
    [DbContext(typeof(CityEnergyModelingContext))]
    partial class CityEnergyModelingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "tiger", "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "topology", "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id")
                        .HasColumnOrder(1);

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id")
                        .HasColumnOrder(2);

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geometry")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("buildings_pkey");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex(new[] { "Id" }, "IX_buildings_id");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.BuildingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("residential_area")
                        .HasColumnOrder(4);

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer")
                        .HasColumnName("building_id")
                        .HasColumnOrder(1);

                    b.Property<int?>("BuiltYear")
                        .HasColumnType("integer")
                        .HasColumnName("built_year")
                        .HasColumnOrder(2);

                    b.Property<int>("RegistryId")
                        .HasColumnType("integer")
                        .HasColumnName("registry_id")
                        .HasColumnOrder(5);

                    b.Property<int>("ResidentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("residents_count")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("building_information_pkey");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "IX_building_information_id");

                    b.ToTable("building_information", (string)null);
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("MinZoom")
                        .HasColumnType("integer")
                        .HasColumnName("min_zoom")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasColumnOrder(2)
                        .HasDefaultValueSql("''::text");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("name_native")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("''::text");

                    b.Property<NpgsqlPoint>("NorthWestPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("point")
                        .HasColumnName("north_west_point")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("'(0,0)'::point");

                    b.Property<NpgsqlPoint>("SouthEastPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("point")
                        .HasColumnName("south_east_point")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("'(0,0)'::point");

                    b.HasKey("Id")
                        .HasName("cities_pkey");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinZoom = 11,
                            Name = "Ivanovo",
                            NativeName = "Иваново",
                            NorthWestPoint = new NpgsqlTypes.NpgsqlPoint(57.093009000000002, 40.661774000000001),
                            SouthEastPoint = new NpgsqlTypes.NpgsqlPoint(56.903770999999999, 41.307220000000001)
                        });
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.CityDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id")
                        .HasColumnOrder(1);

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geometry")
                        .HasColumnOrder(2);

                    b.Property<int?>("HeatingStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("areas_pkey");

                    b.HasIndex("CityId");

                    b.HasIndex("HeatingStationId");

                    b.ToTable("city_districts", (string)null);
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.HeatingPipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DObr")
                        .HasColumnType("numeric")
                        .HasColumnName("d_obr")
                        .HasColumnOrder(2);

                    b.Property<decimal>("DPod")
                        .HasColumnType("numeric")
                        .HasColumnName("d_pod")
                        .HasColumnOrder(1);

                    b.Property<MultiLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiLineString,4326)")
                        .HasColumnName("geometry")
                        .HasColumnOrder(3);

                    b.HasKey("Id")
                        .HasName("heating_pipes_pkey");

                    b.HasIndex(new[] { "Id" }, "IX_heating_pipes_id");

                    b.ToTable("heating_pipes", (string)null);
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.HeatingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id")
                        .HasColumnOrder(2);

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geometry")
                        .HasColumnOrder(3);

                    b.Property<double>("NominalPower")
                        .HasColumnType("double precision")
                        .HasColumnName("nominal_power")
                        .HasColumnOrder(1);

                    b.HasKey("Id")
                        .HasName("heating_stations_pkey");

                    b.HasIndex("CityId");

                    b.HasIndex(new[] { "Id" }, "IX_heating_stations_id");

                    b.ToTable("heating_stations", (string)null);
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.Building", b =>
                {
                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.City", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId");

                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.CityDistrict", "CityDistrict")
                        .WithMany("Buildings")
                        .HasForeignKey("DistrictId");

                    b.Navigation("City");

                    b.Navigation("CityDistrict");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.BuildingInfo", b =>
                {
                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.Building", "Building")
                        .WithOne("BuildingInfo")
                        .HasForeignKey("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.BuildingInfo", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.CityDistrict", b =>
                {
                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.City", "City")
                        .WithMany("CityDistricts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.HeatingStation", "HeatingStation")
                        .WithMany("CityDistricts")
                        .HasForeignKey("HeatingStationId");

                    b.Navigation("City");

                    b.Navigation("HeatingStation");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.HeatingStation", b =>
                {
                    b.HasOne("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.City", "City")
                        .WithMany("HeatingStations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.Building", b =>
                {
                    b.Navigation("BuildingInfo");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.City", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("CityDistricts");

                    b.Navigation("HeatingStations");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.CityDistrict", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Ispu.Gis.EnergyBalances.Infrastructure.Persistence.Entities.HeatingStation", b =>
                {
                    b.Navigation("CityDistricts");
                });
#pragma warning restore 612, 618
        }
    }
}
